### ISSUE TITLE
Scope of project?

### ISSUE THREAD

**Issue by PaulWieland** [apearson/node-red-contrib-insteon#4]
Hey @apearson I just found this node and successfully got it working with my USB PLM connected to a raspi 4 (node red in docker).

I've been thinking about trying to write something myself for a while, but you've got a really great start (although there doesn't seem to be much in the way of examples or documentation).

I was thinking about creating four nodes: Device Input, Device Output, Scene Input, Scene Output - this was to try and mimic the input/ouput nomenclature that node-red has (like for MQTT).

The input nodes would let you choose a target device or scene and then send it a command (On, Off, level, etc), and the output nodes would be like subscribers which listen for a device or scene to go to the specified state (Motion detected, Switched On, etc). 

I hadn't figured out the logistics of naming the devices & scenes...

I also thought about building a node-red-ui for managing links, but that's another story.

Anyway, what is your vision for the project? Are you planning to just keep it a single node that lets you send commands to the PLM or something more than that?

I really want to have all of my insteon control and bridge with Apple HomeKit in node-red.

**Comment by apearson** [comment]
Hi @PaulWieland,

Awesome, I'm glad you got it working! Were there any problems that you ran into? 

This project was and has been my side project for a while and I've really just built out what I've needed to my own Insteon network.

I've envisioned this project being a full alternative to the Insteon hub and other software like Indigo Pro but for Node-RED and free to all. 

I've been thinking about the same four node you've been thinking of (device in, device out, scene/group in, scene/group out).

I really like your idea for the input and output nodes.  I was also going to take it a step further once I had the basic device in/out nodes and have a Keypad node that would be able to manage all the individual features of different devices.  This device node would also output any message coming from that device and would sit in the middle of flows. 

Anyway, this is all in my head for the future for when I get around to it.  I'd welcome any PRs and wouldn't mind discussing what you think this project needs for a 1.0.0 release to the public.

**Comment by PaulWieland** [comment]
The only problem I encountered was a permission issue with Node Red being able to access the serial device. This is further complicated by docker, but I did get it to work.

One other comment is that it seems that the node dumps the entire link database (or at least the info command) to the debug console on every deploy. I would recommend changing that.

I have to spend some more time with your library and the insteon docs to understand what's going on exactly. I'm not sure what format the payload should be for the various commands (e.g. I tried, but failed to get the simple `setLed` command to work).

Also - do you have any example flows you could share?

**Comment by apearson** [comment]
I ran into the same problems getting Node-RED able to access the serial device along with docker passing the serial device into Node-RED.  Glad you got it working. 

The behavior that you're seeing is every packet getting send out of the node.  The best bet would be to filter packets coming out based on id and type before using them.  I don't really want to restrict this functionality in the PLM because there are some use cases that would use the db record packets.  

The setLed command doesn't work while the modem is in autoLed mode.  I'll make sure to put this in the docs for others to know. There are a couple gotchas here and there but I'm attempting to clean up the rough edges without restricting functionality. 

This is the testing harness I've been using to test with. 

https://gist.github.com/apearson/9dfa36d3d927c38ef7c8f06be14f8df3

**Comment by jtmoderate876** [comment]
@apearson & @PaulWieland - I am interested in what you are doing and what can it currently do?
Today I use a "driver" called Insteon-MQTT:
https://github.com/TD22057/insteon-mqtt
that was written for the home automation system called HAS but, because it uses generic MQTT, it also works great with Node-RED. It is well done.

What it doesn't have is easy device management. Instead you fill out a configuration file (in YAML), defining all of your Insteon devices.

It would be nice to bring Insteon right within Node-RED. I think that might be what you two are building toward.

Any video or overview (ppt?) that you could throw together on where things stand and what this can do?

**Comment by PaulWieland** [comment]
Most of the work at the moment is happening in the underlying [insteon-plm](https://github.com/apearson/insteon-plm) library.

Right now the Node-RED node for this gives you a raw PLM input/output node that can accept and send messages, but we have the following idea:

- PLM Config Node - configure the connection to the PLM, display links, add & remove devices
- PLM Node - more of a raw interface in case you have to work around something the nodes don't natively support
- Device Config Node - configure the device, manage insteon device settings, add/remove links
- Subscribe node - listen for device events (switched on, off, motion detected, etc) and trigger a flow
- Command node - send command to device (turn off, go to brightness level, etc)
- Scene config node -tbd
- Scene subscribe node - listen for scene commands and trigger a flow
- Scene command node - send a command to a scene

Right now the PLM Config Node, Device Config Node and Subscribe node are in development under my fork. Working on getting the underlying add/link remove/unlink device code working as desired.

https://node-red.slack.com/files/U8N92T8GP/FQC1Z203X/untitled.mov

**Comment by jtmoderate876** [comment]
That looks like a LOT of functionality already implemented.
I will have a go at it this weekend.

**Comment by PaulWieland** [comment]
There's still much to do. The add/remove device doesn't exactly work yet. Subscribe node doesn't do anything yet, config panels need to be started, etc.

**Comment by apearson** [comment]
@jtmoderate876  Let me know how it works for you.  Always looking for more feedback on these kinds of projects

**Comment by apearson** [comment]
Going to close this as this discussion seems to be complete
